language: python
    python:
        - "3.8"

addons:
    chrome: stable

before-install:
    - google-chrome-stable --headless

install:
    - pip install pipenv
    - pipenv install

env: DJANGO_SETTINGS_MODULE="settings.travis"

services:
    - postgresql

before_script:
    - cd purbeurre/

script:
    - pytest
