language: python
python:
    - "3.8"
addons:
    apt:
        sources:
            - google-chrome

install:
    - pip install pipenv
    - pipenv install

env: 
    - DJANGO_SETTINGS_MODULE="settings.travis"

services:
    - postgresql

before script:
    - cd purbeurre/

script:
    - pytest
