language: python
python:
    - "3.8"
addons:
    chrome: stable

install:
    - pip install pipenv
    - pipenv install

env: 
    - DJANGO_SETTINGS_MODULE="settings.travis"

services:
    - postgresql
  
script:
        - purbeurre/pytest
