language: python
python:
        - "3.8"

install:
        - pip install pipenv
        - pipenv install

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

services:
        - postgresql

before_script:
        - cd purbeurre/
script:
        - pytest
