language: python
python:
    - "3.8"
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable


install:
    - pip install pipenv
    - pipenv install

env: 
    - DJANGO_SETTINGS_MODULE="settings.travis"

services:
    - postgresql

before script:
    - wget http://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.8/bin/
    - export CHROME_BIN=chromium-browser
    - cd purbeurre/

script:
    - pytest