language: python
python:
        - "3.8"
dist: xenial
addons:
  chrome: stable
install:
        - pip install pipenv
        - pipenv install

env: DJANGO_SETTINGS_MODULE="settings.travis"

services:
        - postgresql

before_script:
        - cd purbeurre/
script:
        - pytest
