# Generated by Django 3.1.3 on 2020-12-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='unkonw', max_length=300)),
                ('source', models.URLField(default='unkonw', max_length=500)),
                ('image', models.URLField(default='unkonw', max_length=500)),
                ('nutrition_grade', models.CharField(default='?', max_length=1)),
                ('name', models.CharField(default='unkonw', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nutriment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swap_food.aliment')),
                ('nutriment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swap_food.nutriment')),
            ],
        ),
        migrations.AddField(
            model_name='aliment',
            name='nutriments',
            field=models.ManyToManyField(through='swap_food.Nutrition', to='swap_food.Nutriment'),
        ),
    ]
