# Generated by Django 3.1.3 on 2020-11-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliments',
            name='photo',
            field=models.URLField(max_length=500),
        ),
    ]
