# Generated by Django 3.1.3 on 2020-12-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0002_auto_20201127_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additive_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergens', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=300)),
                ('additive', models.ManyToManyField(to='swap_food.Additive')),
            ],
        ),
        migrations.DeleteModel(
            name='Aliments',
        ),
    ]
