# Generated by Django 3.1.3 on 2020-12-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0003_auto_20201201_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliment',
            name='additive',
        ),
        migrations.AddField(
            model_name='aliment',
            name='image',
            field=models.URLField(default='no_image', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliment',
            name='name',
            field=models.CharField(default='name_error', max_length=200),
            preserve_default=False,
        ),
    ]
