# Generated by Django 3.1.3 on 2020-12-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0004_auto_20201201_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='grade_food',
            field=models.CharField(default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='aliment',
            name='image_s',
            field=models.URLField(default='unkonw', max_length=500),
        ),
        migrations.AddField(
            model_name='aliment',
            name='ingredients',
            field=models.TextField(default='unkonw'),
        ),
        migrations.AddField(
            model_name='aliment',
            name='store',
            field=models.CharField(default='unkonw', max_length=100),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='allergens',
            field=models.CharField(default='unkonw', max_length=500),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='category',
            field=models.CharField(default='unkonw', max_length=300),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='image',
            field=models.URLField(default='unkonw', max_length=500),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='name',
            field=models.CharField(default='unkonw', max_length=200),
        ),
    ]
