# Generated by Django 3.1.3 on 2020-12-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0005_auto_20201206_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additive',
            old_name='additive_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='aliment',
            name='additive',
            field=models.ManyToManyField(to='swap_food.Additive'),
        ),
    ]
