# Generated by Django 3.1.3 on 2020-12-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0006_auto_20201206_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliment',
            old_name='additive',
            new_name='additives',
        ),
    ]
