# Generated by Django 3.1.3 on 2020-12-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0009_auto_20201207_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='store',
            field=models.CharField(default='unkonw', max_length=200),
        ),
    ]
