# Generated by Django 3.1.3 on 2020-12-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0010_auto_20201211_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliment',
            old_name='image_s',
            new_name='source',
        ),
    ]
