# Generated by Django 3.1.3 on 2020-12-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='aliments_saved',
            field=models.ManyToManyField(to='swap_food.Aliment'),
        ),
    ]
