# Generated by Django 3.1.7 on 2021-04-23 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myfood',
            old_name='aliment',
            new_name='aliment_pref',
        ),
        migrations.RenameField(
            model_name='myfood',
            old_name='myuser',
            new_name='myuser_pref',
        ),
        migrations.RemoveField(
            model_name='myfood',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='aliments_saved',
        ),
        migrations.AddField(
            model_name='myuser',
            name='aliments_pref',
            field=models.ManyToManyField(related_name='pref', through='users.Myfood', to='swap_food.Aliment'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('aliment_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swap_food.aliment')),
                ('myuser_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='aliments_rate',
            field=models.ManyToManyField(related_name='rate', through='users.Rating', to='swap_food.Aliment'),
        ),
    ]
