# Generated by Django 3.1.3 on 2020-12-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_myuser_aliments_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='aliments_saved',
            field=models.CharField(default='unkonw', max_length=300),
        ),
    ]
