# Generated by Django 3.1.3 on 2020-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0001_initial'),
        ('users', '0004_myuser_aliments_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(default='unkonw', max_length=300)),
                ('aliments', models.ManyToManyField(to='swap_food.Aliment')),
            ],
        ),
    ]
