# Generated by Django 3.1.3 on 2020-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_food', '0001_initial'),
        ('users', '0005_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='aliments_saved',
        ),
        migrations.AddField(
            model_name='myuser',
            name='aliments_saved',
            field=models.ManyToManyField(to='swap_food.Aliment'),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
